name: Test CI
on:
  push:
    paths:
      - 'tests/SysInfo_test.ring'
      - 'lib.ring'
      - 'constants.ring'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        uses: ysdragon/ring-action@v1.0.6
        with:
          file: "tests/SysInfo_test.ring"